In [ ]:
# Functional style code - Single line Code
# -----------------------------------------
lambda
comprehension 
generator
map filter enumerate
|
Database ; webscrabing ; json ; numpy ; pandas 

In [ ]:
lambda
------
 |->unnamed function - this is not block style code
 |->function call with arguments return some value
    ..............................................
 |-> lambda <list of arguments>:<basic_Operation>
                                  arithmetic;relational;logical;membership;external functionCall etc

In [1]:
'''named function block'''
def f1(a1,a2):
    return a1+a2

f1(10,20)

30

In [2]:
lambda a1,a2:a1+a2

<function __main__.<lambda>(a1, a2)>

In [3]:
f2 = lambda a1,a2:a1+a2
f2(10,20)

30

In [4]:
f3=lambda a:a.upper()
f3('abc')

'ABC'

In [5]:
def f4(a):
    return a.upper()

f4('abc')

'ABC'

In [6]:
f5=lambda a1,a2: a1 > a2
f5(10,20)

False

In [7]:
f5(150,25)

True

In [9]:
def fx(a=0):
    if a > 100 and a <200:
        a = a + 150
        return a
    elif a > 500 and a < 600:
        a = a + 550
        return a
    else:
        return a+600
    
fx() 
fx(10)
fx(50)

In [10]:
f5 = lambda a1:fx(a1)
f5(120)

270

In [11]:
f5(560)

1110

In [12]:
f5(700)

1300

In [13]:
# list comprehension - list append operation
L = []
for var in range(1,6):
    result = var + 100
    L.append(result)
L

[101, 102, 103, 104, 105]

In [ ]:
Syntax:-
---------
[variable for variable in <collection>]
          --------(1)-----------
---(2)----

In [14]:
[var for var in range(1,6)]

[1, 2, 3, 4, 5]

In [15]:
[var+100 for var in range(1,6)]

[101, 102, 103, 104, 105]

In [17]:
# list comprehension - list append operation
L = []
for var in range(1,6):
    if (var >3):
        result = var + 100
        L.append(result)
    else:
        result = var + 500
        L.append(result)
L

[501, 502, 503, 104, 105]

In [18]:
[var+100 if var > 3 else var+500 for var in range(1,6)]

[501, 502, 503, 104, 105]

In [19]:
d={}
d['K1']=[var+100 if var > 3 else var+500 for var in range(1,6)]
d

{'K1': [501, 502, 503, 104, 105]}

In [20]:
L = []
for var in range(1,6):
    if (var >3):
        result = var + 100
        L.append(result)
        
L

[104, 105]

In [21]:
[var+100 for var in range(1,6) if var >3]

[104, 105]

In [33]:
print(type({}))

s1 = {1,2,3,4}
print(type(s1))

d1 = {'K1':1,'K2':2}
print(type(d1))

<class 'dict'>
<class 'set'>
<class 'dict'>


In [ ]:
[value for iterable ]

{key: value for iterable}

In [35]:
print({var+100 for var in range(1,6)})

print(type({var+100 for var in range(1,6)}))


{101, 102, 103, 104, 105}
<class 'set'>


In [36]:
{'K': var for var in range(1,6)}

# {'K':1}
# {'K':2}
# ..
#{'K':5}

{'K': 5}

In [23]:
{'K'+str(var):var+100 for var in range(1,6)}

{'K1': 101, 'K2': 102, 'K3': 103, 'K4': 104, 'K5': 105}

In [27]:
{'K'+str(var):var+100 for var in range(1,6)}


{'K1': 101, 'K2': 102, 'K3': 103, 'K4': 104, 'K5': 105}

In [37]:
d={}
for var in range(1,6):
    if(var >3):
        d['K'+str(var)]=var+100
    else:
        d['K'+str(var)]=var+500
        
d

{'K1': 501, 'K2': 502, 'K3': 503, 'K4': 104, 'K5': 105}

In [39]:
# {'Key':Value}

{'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}
# ----------- ====================================================

{'K1': 501, 'K2': 502, 'K3': 503, 'K4': 104, 'K5': 105}

In [41]:
"K"+str(1)

'K1'

In [42]:
10+20

30

In [43]:
"a"+"b"

'ab'

In [45]:
str(5)+str(6)

'56'

In [46]:
mydict = {}

mydict['prod1']={'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}
mydict['prod2']=[v+100 for v in range(1,15,3)]

In [47]:
mydict

{'prod1': {'K1': 501, 'K2': 502, 'K3': 503, 'K4': 104, 'K5': 105},
 'prod2': [101, 104, 107, 110, 113]}

In [48]:
{'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}.items()

dict_items([('K1', 501), ('K2', 502), ('K3', 503), ('K4', 104), ('K5', 105)])

In [49]:
{'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}.keys()

dict_keys(['K1', 'K2', 'K3', 'K4', 'K5'])

In [50]:
{'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}.values()

dict_values([501, 502, 503, 104, 105])

In [51]:
'K3' in {'K'+str(var):var+100 if var >3 else var+500 for var in range(1,6)}

True

In [ ]:
# generator
# -------------
function iterate over a sequence of values
         -------------------------
             yields values one at a time
       
    we can use multiple yield - pausing its state between yields
    
function return value // exit from definition
function yield value //state of the function is saved ->resume ...

In [54]:
def f1():
    return 10

def f2():
    yield 10
    
print(type(f1),type(f2))
print(type(f1()),type(f2()))

<class 'function'> <class 'function'>
<class 'int'> <class 'generator'>


In [55]:
def f1():
    return 10  # exit from function definition
    print("This line won't display")
    return 20

f1()

10

In [56]:
def f2():
    yield 10
    print("This line will display")
    yield 20
    yield 30,40,50
    yield "D1",["D2","D2"]

In [57]:
f2()

<generator object f2 at 0x000001CA0193C640>

In [ ]:
# next(genobject) ->value .... StopIteration   

# <or>
# for iterable      for variable in genObject:
#                           ...   # we won't get stopiteration 

# <or>

# we can type cast to list     ->  list(genObject)

In [58]:
genobj = f2()

In [59]:
print(next(genobj))
print(next(genobj))
print(next(genobj))
print(next(genobj))
print(next(genobj))

10
This line will display
20
(30, 40, 50)
('D1', ['D2', 'D2'])


StopIteration: 

In [60]:
genobj = f2()

In [61]:
for var in genobj:
    print(var)

10
This line will display
20
(30, 40, 50)
('D1', ['D2', 'D2'])


In [62]:
genobj = f2()
list(genobj)

This line will display


[10, 20, (30, 40, 50), ('D1', ['D2', 'D2'])]

In [63]:
def mywalk():
    yield "D1",["Sub1","Sub2","Sub3"],["F1","F2","F3"]

In [64]:
list(mywalk())

[('D1', ['Sub1', 'Sub2', 'Sub3'], ['F1', 'F2', 'F3'])]

map
---//reduce block style code
  // omit for loop

map(function,<collection>) -> generator_result 
      |            |
    we can use    comprehension <or> iterable 
      lambda
 ----//used arithmetic,relational,logical...
    
filter(function,<collection>) ->generator_result
-----//filter only - filter true value only
     //not used for arithmetic 

In [65]:
L = []

def f1(a):
    return a+100

for var in range(1,6):
    r = f1(var)
    L.append(r)
    
L

[101, 102, 103, 104, 105]

In [67]:
list(map(lambda a:a+100,range(1,6)))

[101, 102, 103, 104, 105]

In [68]:
list(map(lambda a:a>3,range(1,6)))

[False, False, False, True, True]

In [69]:
L = []

def f1(a):
    if(a>3):
        return True
    else:
        return False

for var in range(1,6):
    r = f1(var)
    L.append(r)
    
L

[False, False, False, True, True]

In [70]:
list(filter(lambda a:a>3,range(1,6)))

[4, 5]

In [71]:
open('E:\\emp.csv')        

<_io.TextIOWrapper name='E:\\emp.csv' mode='r' encoding='cp1252'>

In [72]:
fobj = open('E:\\emp.csv')
list(fobj)

['eid,ename,edept,eplace,ecost\n',
 '101,raj,sales,pune,1000\n',
 '102,leo,prod,bglore,2000\n',
 '103,paul,HR,chennai,3000\n',
 '104,anu,hr,hyderabad,4000\n',
 '456,kumar,sales,bglore,3000\n',
 '105,zion,Hr,mumbai,5000\n',
 '106,bibu,sales,bglore,1450\n',
 '107,theeb,sales,noida,4590\n',
 '108,bibu,sales,bglore,5000\n',
 '113,kumar,prod,hyderabad,5423']

In [74]:
fobj = open('E:\\emp.csv')
for var in fobj:
    print(var.strip())

eid,ename,edept,eplace,ecost
101,raj,sales,pune,1000
102,leo,prod,bglore,2000
103,paul,HR,chennai,3000
104,anu,hr,hyderabad,4000
456,kumar,sales,bglore,3000
105,zion,Hr,mumbai,5000
106,bibu,sales,bglore,1450
107,theeb,sales,noida,4590
108,bibu,sales,bglore,5000
113,kumar,prod,hyderabad,5423


In [75]:
list(map(lambda a:a,open('E:\\emp.csv')))

['eid,ename,edept,eplace,ecost\n',
 '101,raj,sales,pune,1000\n',
 '102,leo,prod,bglore,2000\n',
 '103,paul,HR,chennai,3000\n',
 '104,anu,hr,hyderabad,4000\n',
 '456,kumar,sales,bglore,3000\n',
 '105,zion,Hr,mumbai,5000\n',
 '106,bibu,sales,bglore,1450\n',
 '107,theeb,sales,noida,4590\n',
 '108,bibu,sales,bglore,5000\n',
 '113,kumar,prod,hyderabad,5423']

In [76]:
d={}
d['CSV']=list(map(lambda a:a,open('E:\\emp.csv')))
d

{'CSV': ['eid,ename,edept,eplace,ecost\n',
  '101,raj,sales,pune,1000\n',
  '102,leo,prod,bglore,2000\n',
  '103,paul,HR,chennai,3000\n',
  '104,anu,hr,hyderabad,4000\n',
  '456,kumar,sales,bglore,3000\n',
  '105,zion,Hr,mumbai,5000\n',
  '106,bibu,sales,bglore,1450\n',
  '107,theeb,sales,noida,4590\n',
  '108,bibu,sales,bglore,5000\n',
  '113,kumar,prod,hyderabad,5423']}

In [79]:
#help(enumerate)

enumerate(collection,start=0)
                           |___ we can change
list(enumerate('abc'))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [80]:
list(enumerate('abc',5))

[(5, 'a'), (6, 'b'), (7, 'c')]

In [81]:
L=['D1','D2','D3','D4','D5']

for var in enumerate(L):
    print(var)

(0, 'D1')
(1, 'D2')
(2, 'D3')
(3, 'D4')
(4, 'D5')


In [82]:
L=['D1','D2','D3','D4','D5']

for var in enumerate(L,3):
    print(var)

(3, 'D1')
(4, 'D2')
(5, 'D3')
(6, 'D4')
(7, 'D5')


In [83]:
L=['D1','D2','D3','D4','D5']

for var in enumerate(L,1):
    print(var)

(1, 'D1')
(2, 'D2')
(3, 'D3')
(4, 'D4')
(5, 'D5')


In [84]:
L=['D1','D2','D3','D4','D5']

for var in enumerate(L,1):
    v1,v2 = var # multiple initialization
    print(f'{v1} - {v2}')

1 - D1
2 - D2
3 - D3
4 - D4
5 - D5


# Task
open sysinfo.log file 
https://github.com/Palanikarthikeyan/DataScience__Science-Adv-/blob/main/sysinfo.log
|
use enumerate - set index number 1
|
filter line number 10 - 15 line contents 

In [86]:
enumerate(open('sysinfo.log'),1)

In [91]:
for var in enumerate(open('sysinfo.log'),1):
    line,data = var 
    if(line >=10 and line <=15):
        print(line,data.strip())

10 host07:10.20.30.45:98.45,99,32,90,120,400,99,80.44
11 host08:10.20.30.46:98.25,99,32,90,120,200,99,90.45
12 
13 
14 host09:10.20.30.47:88.45,99,32,90,120,500,99,80.44
15 host09:10.20.30.47:98.75,99,32,90,120,200,99,80.43


In [92]:
import re
# ^$ - empty line
for var in enumerate(open('sysinfo.log'),1):
    line,data = var 
    if(line >=10 and line <=15):
        if not(re.search('^$',data)): # ignore empty lines 
            print(line,data.strip())

10 host07:10.20.30.45:98.45,99,32,90,120,400,99,80.44
11 host08:10.20.30.46:98.25,99,32,90,120,200,99,90.45
14 host09:10.20.30.47:88.45,99,32,90,120,500,99,80.44
15 host09:10.20.30.47:98.75,99,32,90,120,200,99,80.43


python ------------------------ database 
--------                        -----------
 DS+function                        SQL
 class,object
 
 s='select *from table'              select *from table //SQL
   |__________________|                   |
     |->string                            |
                                          |
     ----------------<--------------------|
         python_understanding_format
              str,list,tuple,dict
               generator ...

E:\D2>python
Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import sqlite3
>>> sqlite3.connect
<built-in function connect>
>>>
>>> sqlite3.connect("products.db")
<sqlite3.Connection object at 0x00000274B1372E30>
>>>
>>> con  = sqlite3.connect("products.db")
>>> con.cursor
<built-in method cursor of sqlite3.Connection object at 0x00000274B1372F20>
>>>
>>> con.cursor()
<sqlite3.Cursor object at 0x00000274B1458840>
>>>
>>> sth = con.cursor()
>>>
>>> sth.execute("create table pT (pID INT,pName Text,pCost INT)")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> sth.execute("insert into pT(pID,pName,pCost) values(101,'prodA',1000)")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> sth.execute("insert into pT(pID,pName,pCost) values(102,'prodB',2000)")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> va=103
>>> vb='prodC'
>>> vc=3000
>>>
>>> sth.execute("insert into pT(pID,pName,pCost) values(?,?,?)",(va,vb,vc))
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> sth.execute("select *from pT")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> sth.fetchone()
(101, 'prodA', 1000)
>>> sth.fetchone()
(102, 'prodB', 2000)
>>> sth.fetchone()
(103, 'prodC', 3000)
>>> sth.fetchone()
>>>
>>> sth.execute("select *from pT")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> sth.fetchall()
[(101, 'prodA', 1000), (102, 'prodB', 2000), (103, 'prodC', 3000)]
>>>
>>>
>>> sth.execute("select *from pT")
<sqlite3.Cursor object at 0x00000274B1417E40>
>>>
>>> list(sth) # generator
[(101, 'prodA', 1000), (102, 'prodB', 2000), (103, 'prodC', 3000)]
>>> con.commit()
>>> con.close()
>>>
>>>
>>> import sqlite3
>>> sqlite3.connect("products.db")
<sqlite3.Connection object at 0x00000274B1373010>
>>>
>>> db_con = sqlite3.connect("products.db")
>>> sth=db_con.cursor()
>>> sth.execute("select *from pT")
<sqlite3.Cursor object at 0x00000274B1459940>
>>> list(sth)
[(101, 'prodA', 1000), (102, 'prodB', 2000), (103, 'prodC', 3000)]
>>>

In [93]:
import sqlite3
conn = sqlite3.connect('Test1.db')
sth = conn.cursor()
sth.execute("create table T1(f1 INT,f2 Text)")
sth.execute("insert into T1(f1,f2) values(101,'Data1')")
sth.execute("insert into T1(f1,f2) values(102,'Data2')")
sth.execute("insert into T1(f1,f2) values(103,'Data3')")
sth.execute("insert into T1(f1,f2) values(104,'Data4')")

In [94]:
sth.execute("select *from T1")

In [95]:
list(sth)

[(101, 'Data1'), (102, 'Data2'), (103, 'Data3'), (104, 'Data4')]

In [96]:
sth.execute("select *from T1 where f1 >102")

In [97]:
list(sth)

[(103, 'Data3'), (104, 'Data4')]

In [98]:
conn.close()

In [100]:
db_con = sqlite3.connect('Test1.db')
sth = db_con.cursor()
sth.execute("select *from T1")

In [101]:
list(sth)

[]

In [ ]:
# commit() was not used 

In [ ]:
enumerate(collection,indexNumber)
zip(collection1,collection2,....) - combined - Combine multiple iterables element by element

In [102]:
zip(['sales','prod','Qa','CRM'],[101,102,103,104])

In [103]:
zipped_obj = zip(['sales','prod','Qa','CRM'],[101,102,103,104])

list(zipped_obj)

[('sales', 101), ('prod', 102), ('Qa', 103), ('CRM', 104)]

In [104]:
zipped_obj = zip(['sales','prod','Qa','CRM'],[101,102,103,104])
for var in zipped_obj:
    print(var)

('sales', 101)
('prod', 102)
('Qa', 103)
('CRM', 104)


In [105]:
zip(['D1','D2','D3'])

In [106]:
list(zip(['D1','D2','D3']))

[('D1',), ('D2',), ('D3',)]

In [107]:
list(enumerate(['D1','D2','D3']))

[(0, 'D1'), (1, 'D2'), (2, 'D3')]

In [ ]:
Data Source 
------------
 webcontent
 ----------
        ->page
        ->data
        
Client
   input_ -> [empID] --------------->serverCode ----->execute
               Emp Name                                   |
               Emp DOB                                    |
               Emp Dept           ------------<-----------
                -------------//Data            webpage format_
                
webpage = <html>+data
          ..... --------//data only
            |     |
            |   json 
            |
            webpage - webscraping - clean the tags - get the data only
            
response1- webpage                     Vs              response2 - data 
Content-Type: text/html                                Content-Type: application/json
             
<html>                                               [ename,edob,eplace]
<head>                                                         <or>
<title>...</title>                                   {eid:[ename,edob,eplace]}
<body>                                              -----------------------------//Data only
<p>Emp name:{{ename}}</p>
<h1>Emp DOB:{{edob}}</h1>
<h2>Emp Place:{{eplace}}</h2>
..
</html>

json 
-----
 ->store and exchange the data between webapplications
 ->Dashboard --------->Customer/Team
   ---------
   ---------
     |--->json ---------> upload the json file ->Dashboard is ready
    
In python ----------- In Json
int                    int
float                  float
str                    str
list/tuple ----------> Array
---                    -----//mutable
|_________________________|

dict -----------------> object//mutable

True,False ------------> true,false
None --------------------> null

import json <== builtin module

json.dumps(<python_str>) - Convert from python to json

json.loads(<json_str>) - Convert from json to python


In [108]:
import json
product_app = {"pid":['p101','pA',1000]}
print(type(product_app))

<class 'dict'>


In [109]:
json.dumps(product_app) # convert to json object

'{"pid": ["p101", "pA", 1000]}'

In [110]:
jd = json.dumps(product_app)

json.loads(jd) # from json to python

{'pid': ['p101', 'pA', 1000]}

import requests 
requests.get(URL) ->status_code 
                    --------------> 200 OK  ; != 200 - failed
|
Header info - URL web header - Type of response ; size; etc.,
|
download the content -> text - attribute


In [111]:
import requests
requests.get('https://www.google.com')

<Response [200]>

In [112]:
r = requests.get('https://www.google.com')
r.status_code

200

In [113]:
r.headers

{'Date': 'Tue, 11 Mar 2025 09:37:00 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-igzHUYY0YXd714uje7pAiA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'Accept-CH': 'Sec-CH-Prefers-Color-Scheme', 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': 'AEC=AVcja2fce2hMKHn0SP6Hw_iveTDJ1kJcT3A0-watLlmfXB_7OSlrpdA1aM8; expires=Sun, 07-Sep-2025 09:37:00 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=522=ib4J9H1q6JlmjpXxxg3q8E30teMEjWfmeVA2WgKeqtR2MP0mYt2886ATQwGhqhdSHVW_9XUbFjxBzeeh5Qo-MDK2DMaO3AJhU38GL6h0gSSP4wG9h2UXg_LHEP98b00Z6pFaqhwvPx_oNZBOlpjzOolEL4hv2XBPYc3zPgEHqihDsspmwe-clU7_sNvGrAFOsSXun

In [114]:
r.headers['Content-Type']

'text/html; charset=ISO-8859-1'

In [116]:
r = requests.get('https://api.github.com/repos/hadley/ggplot2/commits')
r.status_code

200

In [117]:
r.headers['Content-Type']

'application/json; charset=utf-8'

In [118]:
r.text

'[{"sha":"1800a9af9e2d29292b67a236f654e2bacb524bae","node_id":"C_kwDNS-7aACgxODAwYTlhZjllMmQyOTI5MmI2N2EyMzZmNjU0ZTJiYWNiNTI0YmFl","commit":{"author":{"name":"Mathieu YECHE","email":"99674960+MathieuYeche@users.noreply.github.com","date":"2025-03-07T17:52:01Z"},"committer":{"name":"GitHub","email":"noreply@github.com","date":"2025-03-07T17:52:01Z"},"message":"fix_6357 (#6358)\\n\\nSee https://github.com/tidyverse/ggplot2/issues/6357","tree":{"sha":"e249ee1f198d5053b2607cd42ba025a804eadb24","url":"https://api.github.com/repos/tidyverse/ggplot2/git/trees/e249ee1f198d5053b2607cd42ba025a804eadb24"},"url":"https://api.github.com/repos/tidyverse/ggplot2/git/commits/1800a9af9e2d29292b67a236f654e2bacb524bae","comment_count":0,"verification":{"verified":true,"reason":"valid","signature":"-----BEGIN PGP SIGNATURE-----\\n\\nwsFcBAABCAAQBQJnyzJBCRC1aQ7uu5UhlAAAwQMQAIxOTfdY0oMHgyBpWrT1G918\\nuEWNJ30YsNsSYefGGVE6Yo+oJqFMeOcrwiU5cMcbAhFHoXpoP7cNGBzHmL1wzhlC\\n2/bzRtCLls+P4CTVlaCXE+3ewUTCi3RreH7GXUBwz

In [119]:
json_data = r.text

In [120]:
python_data = json.loads(json_data) # From json to python
print(type(python_data),len(python_data))

<class 'list'> 30


In [121]:
print(type(python_data[0]),len(python_data[0]))

<class 'dict'> 9


In [ ]:
# requests - download the webcontent 
# bs4  - web scraping 

bs4.BeautifulSoup('Webpage') -> SoupObject.<htmlTag> ->data
                                    <or>
                             -> SoupObject.find('<htmlTag>') ->data
                                    <or>
                             -> SoupObject.find_all('<htmlTag>') -> [data ...data]
                
<a class='id1' img='source'>
 | ----------  -------------//like a dictContent {'class':'id1'} 
 |
outerTag

search - parent - child ; siblings

<html>
<head>
<title>...</title>   title.parent - will get <head>...</head>
<body>
<p> ..</p>
</body>
</head>
</html>

In [122]:
import bs4

In [123]:
r = requests.get('https://www.google.com')
if(r.status_code != 200):
    print('url download is failed')
    exit
    
r.headers['Content-Type']

'text/html; charset=ISO-8859-1'

In [124]:
web_page = r.text

In [125]:
print(type(web_page),len(web_page))

<class 'str'> 19051


In [126]:
import bs4
gpage = bs4.BeautifulSoup(web_page)

In [127]:
gpage.title

<title>Google</title>

In [128]:
gpage.p

<p style="font-size:8pt;color:#70757a">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>

In [131]:
gpage.title.string

'Google'

In [132]:
gpage.find('p')

<p style="font-size:8pt;color:#70757a">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>

In [133]:
gpage.find_all('p')

[<p style="font-size:8pt;color:#70757a">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>]

In [134]:
gpage.find('h1')

In [135]:
gpage.find('a')

<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>

In [136]:
gpage.find('a')['class'] # dict 

['gb1']

In [137]:
d={'K1':'V1'}
d.get('K1') # d['K1'] 

'V1'

In [139]:
# d['K2']  ->KeyError
d.get('K2') ->None

In [140]:
gpage.find('a').get('class')

['gb1']

In [141]:
gpage.find('a')

<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>

In [142]:
gpage.find('a').get('href')

'https://www.google.com/imghp?hl=en&tab=wi'

In [143]:
gpage.find('a').string

'Images'

In [144]:
gpage.find_all('a')

[<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>,
 <a class="gb1" href="https://maps.google.co.in/maps?hl=en&amp;tab=wl">Maps</a>,
 <a class="gb1" href="https://play.google.com/?hl=en&amp;tab=w8">Play</a>,
 <a class="gb1" href="https://www.youtube.com/?tab=w1">YouTube</a>,
 <a class="gb1" href="https://news.google.com/?tab=wn">News</a>,
 <a class="gb1" href="https://mail.google.com/mail/?tab=wm">Gmail</a>,
 <a class="gb1" href="https://drive.google.com/?tab=wo">Drive</a>,
 <a class="gb1" href="https://www.google.co.in/intl/en/about/products?tab=wh" style="text-decoration:none"><u>More</u> »</a>,
 <a class="gb4" href="http://www.google.co.in/history/optout?hl=en">Web History</a>,
 <a class="gb4" href="/preferences?hl=en">Settings</a>,
 <a class="gb4" href="https://accounts.google.com/ServiceLogin?hl=en&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAAQ" id="gb_70" target="_top">Sign in</a>,
 <a href="/advanced_search?hl=en-IN&amp;authuser=

In [148]:
for var in gpage.find_all('a'):
    print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
/preferences?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
/advanced_search?hl=en-IN&authuser=0
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAY
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAc
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAg
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXd

In [149]:
for var in gpage.find_all('a'):
    print(var.string)

Images
Maps
Play
YouTube
News
Gmail
Drive
None
Web History
Settings
Sign in
Advanced search
हिन्दी
বাংলা
తెలుగు
मराठी
தமிழ்
ગુજરાતી
ಕನ್ನಡ
മലയാളം
ਪੰਜਾਬੀ
Advertising
Business Solutions
About Google
Google.co.in
Privacy
Terms


In [150]:
import re
for var in gpage.find_all('a'):
    if(re.search('^(http|https)',var.get('href'))):
        print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAY
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAc
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAg
https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=mr&source=homepage&sa=X&ved=0ahUKEwj74byp5IG

In [156]:
gpage_urls = []

In [157]:
for var in gpage.find_all('a'):
    if(re.search('^(http|https)',var.get('href'))):
        gpage_urls.append(var.get('href'))

In [158]:
gpage_urls

['https://www.google.com/imghp?hl=en&tab=wi',
 'https://maps.google.co.in/maps?hl=en&tab=wl',
 'https://play.google.com/?hl=en&tab=w8',
 'https://www.youtube.com/?tab=w1',
 'https://news.google.com/?tab=wn',
 'https://mail.google.com/mail/?tab=wm',
 'https://drive.google.com/?tab=wo',
 'https://www.google.co.in/intl/en/about/products?tab=wh',
 'http://www.google.co.in/history/optout?hl=en',
 'https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ',
 'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAY',
 'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAc',
 'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAg',
 'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdoz

In [159]:
d={'K1':['D1','D2','D3','D4'],'K2':[10,20,30,40]}
d

{'K1': ['D1', 'D2', 'D3', 'D4'], 'K2': [10, 20, 30, 40]}

In [160]:
d['Google']=gpage_urls # adding new data to an existing dict

In [161]:
d

{'K1': ['D1', 'D2', 'D3', 'D4'],
 'K2': [10, 20, 30, 40],
 'Google': ['https://www.google.com/imghp?hl=en&tab=wi',
  'https://maps.google.co.in/maps?hl=en&tab=wl',
  'https://play.google.com/?hl=en&tab=w8',
  'https://www.youtube.com/?tab=w1',
  'https://news.google.com/?tab=wn',
  'https://mail.google.com/mail/?tab=wm',
  'https://drive.google.com/?tab=wo',
  'https://www.google.co.in/intl/en/about/products?tab=wh',
  'http://www.google.co.in/history/optout?hl=en',
  'https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ',
  'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAY',
  'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGHaHWBtEQ2ZgBCAc',
  'https://www.google.com/setprefs?sig=0_rMXklYNR4YtlL2uj-cdTXdozKJA%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwj74byp5IGMAxV4J7kGH

In [162]:
len(d['Google']) # no.of urls

21

In [163]:
d = {'K1': ['D1', 'D2', 'D3', 'D4','D5','D6','D7'],
 'K2': [10, 20, 30, 40,50,60,70],
 'Google': ['https://www.google.com/imghp?hl=en&tab=wi',
  'https://maps.google.co.in/maps?hl=en&tab=wl',
  'https://play.google.com/?hl=en&tab=w8',
  'https://www.youtube.com/?tab=w1',
  'https://news.google.com/?tab=wn',
  'https://mail.google.com/mail/?tab=wm',
  'https://drive.google.com/?tab=wo']
}

In [164]:
import pandas
pandas.DataFrame(d)

K1  K2                                       Google
0  D1  10    https://www.google.com/imghp?hl=en&tab=wi
1  D2  20  https://maps.google.co.in/maps?hl=en&tab=wl
2  D3  30        https://play.google.com/?hl=en&tab=w8
3  D4  40              https://www.youtube.com/?tab=w1
4  D5  50              https://news.google.com/?tab=wn
5  D6  60         https://mail.google.com/mail/?tab=wm
6  D7  70             https://drive.google.com/?tab=wo

In [ ]:
# python.org
#https://docs.python.org/3/c-api/intro.html#include-files

# dict of list 

# download - requests module
# bs4 module

In [168]:
def download_url(URL):
    r = requests.get(URL)
    if (r.status_code != 200):
        print("Download is failed")
        return 0
    if('text/html' in r.headers['Content-Type']):
        print('response is webpage - do web scraping')
    elif('application/json' in r.headers['Content-Type']):
        print('response is data response')



response is webpage - do web scraping


In [170]:
L=['https://www.google.com','https://api.github.com/repositories/19438/commits',
   'https://www.python.org',
  'https://api.github.com/users/hadley/orgs']

for var in L:
    download_url(var)

response is webpage - do web scraping
response is data response
response is webpage - do web scraping
response is data response


In [181]:
def download_url(URL):
    r = requests.get(URL)
    if (r.status_code != 200):
        print("Download is failed")
        return 0
    if('text/html' in r.headers['Content-Type']):
        print('response is webpage - do web scraping')
        webpage = r.text
        f1(webpage) # functionCall args
    elif('application/json' in r.headers['Content-Type']):
        print('response is data response')
        json_data = r.text
        f2(json_data)  



In [182]:
L=[]

def f1(webpage):
    sobj = bs4.BeautifulSoup(webpage)
    s = sobj.title.string
    for var in sobj.find_all('a'):
        L.append(var.get('href'))
    
def f2(json_data):
    python_data = json.loads(json_data) # from json to python
    print(type(python_data),len(python_data))
    #pprint.pprint(python_data)

In [183]:
URLs=['https://www.google.com','https://api.github.com/repositories/19438/commits',
   'https://www.python.org',
  'https://api.github.com/users/hadley/orgs']

for var in URLs:
    download_url(var)

response is webpage - do web scraping
response is data response
<class 'list'> 30
response is webpage - do web scraping
response is data response
<class 'list'> 10


In [186]:
mydict={}
mydict['Google']=L
len(mydict['Google'])

233

In [187]:
mydict['Google'][-3:]

['/psf-landing/',
 '/about/legal/',
 'https://policies.python.org/python.org/Privacy-Notice/']

In [188]:
d={'Google':['url1','url2','url3'],'Python_org':['urlA','urlB','urlC']}
d

{'Google': ['url1', 'url2', 'url3'], 'Python_org': ['urlA', 'urlB', 'urlC']}

In [189]:
requests.get('https://api.openweathermap.org/data/3.0/onecall/timemachine?lat={lat}&lon={lon}&dt={time}&appid={API key}')

<Response [401]>

In [190]:
requests.get('https://openweathermap.org/weathermap?basemap=map&cities=true&layer=temperature&lat=18.7711&lon=81.3428&zoom=5')

<Response [200]>

In [191]:
r=requests.get('https://openweathermap.org/weathermap?basemap=map&cities=true&layer=temperature&lat=18.7711&lon=81.3428&zoom=5')
r.headers

{'Server': 'nginx/1.24.0', 'Date': 'Tue, 11 Mar 2025 10:56:16 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'private, must-revalidate', 'pragma': 'no-cache', 'expires': '-1', 'Set-Cookie': 'winter_session=eyJpdiI6IjhVZkw1cHBEVTRpK0xyeSs1VHRwMEE9PSIsInZhbHVlIjoieCtxUEgyK0hXZVVva0doNXpxZDA2L0YzMmR6TzVxcTBGdGlOZlBOVlFkTThiRlB5aW5WdXkycnJLaGpiN3hCYzdnbGh6NEJJNGZPbGx5MVR5TGt5bDh2cHJTS1VwUWE2L2E5bWRtSkwzOTkvaVJNMnVSN2E5RlNjWFBWRGZBVTYiLCJtYWMiOiI4OTVkY2ZjYzY5MDVhZTI4MjgxOTBhMTcyMmJjOTAwNDMxNmNjNzlmNDg4NzFmMzM3ODBlZWE3OGVhMGQxZGFmIiwidGFnIjoiIn0%3D; expires=Tue, 11 Mar 2025 12:56:16 GMT; Max-Age=7200; path=/; httponly; samesite=lax', 'Content-Encoding': 'gzip'}

In [194]:
#print(r.text)

In [ ]:
numpy
------
 |->numerical python  
      |->mathematical operation
        

In [195]:
# python list - collection of different types of item

L1 = [10,20,30]
L2 = [15,25,35]
L1+L2

[10, 20, 30, 15, 25, 35]

In [196]:
L1+100

TypeError: can only concatenate list (not "int") to list

In [197]:
L1 > 15

TypeError: '>' not supported between instances of 'list' and 'int'

In [198]:
L1.append("data")
L1

[10, 20, 30, 'data']

In [199]:
import array
print(array.array)

<class 'array.array'>


In [201]:
#help(array.array)
array.array('i')

array('i')

In [203]:
arr = array.array('i') # int
arr.append(10)
arr.append(-1)
arr.append(45)
arr

array('i', [10, -1, 45])

In [204]:
arr.append(56.0)

TypeError: 'float' object cannot be interpreted as an integer

In [205]:
arr

array('i', [10, -1, 45])

In [206]:
arr+100

TypeError: can only append array (not "int") to array

In [207]:
arr >15

TypeError: '>' not supported between instances of 'array.array' and 'int'

In [209]:
import numpy
numpy.array([10,20,30])

array([10, 20, 30])

In [210]:
a1 = numpy.array([10,20,30])
print(type(a1))

<class 'numpy.ndarray'>


In [211]:
a1+100

array([110, 120, 130])

In [212]:
a1 >15

array([False,  True,  True])

In [213]:
L1 = [10,20,30] # list 

A1 = array.array('i',[10,20,30]) # array

NA1 = numpy.array([10,20,30])

print(L1[0],A1[0],NA1[0])

10 10 10


In [214]:
# L1+100 ->Error

# A1+100 ->Error

NA1+100

array([110, 120, 130])

In [215]:
na1 = numpy.array([10,20,30,40,50])
na2 = numpy.array([100,200,300,400,500])
print(na1+na2)
print(na2-na1)
print(na1*5)

[110 220 330 440 550]
[ 90 180 270 360 450]
[ 50 100 150 200 250]


import abcdefghijklmn   ---> import abcdefghijklmn as ab
abcdefghijklmn.fx()          ab.fx() //valid

import D1.D2.abcd  -----------> import D1.D2.abcd as mymodule
D1.D2.abcd.fx()                 mymodule.fx()
D1.D2.xyz.fy()                  mymodule.fy() //valid

import numpy as np
np.array([10,20,30])

In [216]:
import numpy as np
np.__version__

'1.24.3'

In [ ]:
numpy
 --->array creation
 --->N-dArray
 --->attributes
 --->indexing ; slicing
ufnc
 |--->Math function
 |--->statistical function

In [217]:
import numpy as np
np.array([10,20,30,40,50])

array([10, 20, 30, 40, 50])

In [218]:
arr1 = np.array([10,20,30,40,50])
arr1[0]

10

In [219]:
arr1[1:]

array([20, 30, 40, 50])

In [220]:
arr1.dtype

dtype('int32')

In [221]:
np.array([10,20,30,40,50.0]).dtype

dtype('float64')

In [222]:
np.array([10,20,30,40,50.0,'abc']).dtype

dtype('<U32')

In [223]:
np.array([True,False]).dtype

dtype('bool')

In [224]:
np.array([True,False,0]).dtype

dtype('int32')

In [225]:
np.array([10,20,30,40,50]).dtype

dtype('int32')

In [226]:
np.array([10,20,30,40,50],dtype='int64')

array([10, 20, 30, 40, 50], dtype=int64)

In [227]:
a1 = np.array([10,20,30,40,50],dtype='int64')
a1.dtype

dtype('int64')

In [228]:
np.random.rand(5)

array([0.70867388, 0.2595142 , 0.73830998, 0.33620302, 0.07711308])

In [229]:
np.random.rand(5).dtype

dtype('float64')

In [230]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [231]:
a1 = np.array([10,20,30])
print(a1.dtype)
print(a1.ndim) # dimension

int32
1


In [234]:
a1 = np.array([10,20,30])
print(a1.ndim)

a2 = np.array([[10,20,30]])
print(a2.ndim) # 2D Table - row X Col

a3 = np.array([[[10,20,30]]])
print(a3.ndim) # 3D Table - slicing,rowxcols - cube width,height,depth

an = np.array([[[[[10,20]]]]])
an.ndim

1
2
3


5

In [237]:
print(a1,a1[0])
print(a2,a2[0])
print(a2,a2[0],a2[0][0])

[10 20 30] 10
[[10 20 30]] [10 20 30]
[[10 20 30]] [10 20 30] 10


In [239]:
print(a3,a3[0],a3[0][0],a3[0][0][0])

[[[10 20 30]]] [[10 20 30]] [10 20 30] 10


In [240]:
print(a2[0][0])
print(a2[0,0])

10
10


In [241]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
arr.ndim

2

In [243]:
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [245]:
print(arr[1][2])
print(arr[1,2])

70
70


In [246]:
arr.shape

(2, 4)

In [247]:
# change the dimension - based on available of data

a1 = np.array([[10,20,30,33],[40,50,60,77],[35,45,55,42]])
print(a1.ndim,a1.shape)

2 (3, 4)


In [248]:
a1.reshape(4,3) # 4rows X 3cols

array([[10, 20, 30],
       [33, 40, 50],
       [60, 77, 35],
       [45, 55, 42]])

In [249]:
a1.reshape(1,12)

array([[10, 20, 30, 33, 40, 50, 60, 77, 35, 45, 55, 42]])

In [250]:
a1.reshape(2,6)

array([[10, 20, 30, 33, 40, 50],
       [60, 77, 35, 45, 55, 42]])

In [251]:
a1.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [252]:
a1.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [253]:
np.sum(a1)

497

     C1 C2 C3
 R1  10 20 30
 R2  40 50 60

In [254]:
a2 = np.array([[10,20,30],[40,50,60]])
print(np.sum(a2))

210


In [255]:
print(np.sum(a2,axis=0)) # columns

[50 70 90]


In [ ]:
C1 = 10+40 =>50
C2 = 20+50 =>70
C3 = 30+60 =>90

In [256]:
print(np.sum(a2,axis=1)) # row
# R1 -> 10+20+30 ->60
# R2 -> 40+50+60 ->150

[ 60 150]


In [257]:
np.max(a2)

60

In [258]:
np.min(a2)

10

In [259]:
np.mean(a2)

35.0

In [ ]:
np.sum
np.median
np.max
np.min
np.mean
np.unique
np.random
np.arange

mathematical functions
 - abs()
 - sqrt()
..
 -> sin,cos,tan...
 ->log
 ->set operation

In [260]:
a1= np.array([10,20,30])
a2= np.array([40,50,60])
np.union1d(a1,a2) # like set(L1)|set(L2)

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.intersect1d - intersection
np.setdiff1d - difference
np.setxor1d - symmetric_difference 

In [262]:
a3 = np.arange(3,15)
a3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [263]:
a3 > 10

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True])

In [264]:
# boolean indexing

a3[a3 >10] # like filter() - returns True value only

array([11, 12, 13, 14])

# Task
create numpy array - initialize dept name list
- determine dimension
- determine type
- determine shape
- filter - specific dept - apply boolean indexing

In [265]:
dept = np.array(['sales','prod','QA','CRM','DBA','sales','prod','sales'])
print(dept.ndim,dept.dtype,dept.shape)


1 <U5 (8,)


In [266]:
dept == 'sales'

array([ True, False, False, False, False,  True, False,  True])

In [267]:
dept[dept =='sales']

array(['sales', 'sales', 'sales'], dtype='<U5')

In [268]:
# empID empName empDept empCost
#                        ...

empCost = [100,200,300,400,500]
t=0
for var in empCost:
    t=t+var
print(t)

1500


In [269]:
np.sum(empCost) # <== using numpy way

1500

In [270]:
empCost = ['100Rs','Rs200','300$','400INR','500rs']
np.array(empCost).dtype

dtype('<U6')

In [272]:
# np.sum(empCost) -> UFuncTypeError

In [275]:
s='100Rs'
re.sub('[A-Za-z]+','',s) # target string is empty - like delete 

'100'

In [276]:
s='450$'
re.sub('$$','',s)

'450$'

In [277]:
re.sub('\$$','',s)

'450'

In [278]:
re.sub("['A-Za-z']+|[^\w\s]+","","145Rs600$69INR")

'14560069'

In [280]:
empCost = ['100Rs','Rs200','300$','400INR','500rs']

L = []
for var in empCost:
    r = re.sub("['A-Za-z']+|[^\w\s]+","",var)
    L.append(r)
    
L

['100', '200', '300', '400', '500']

In [281]:
def fx(a):
    return int(re.sub("['A-Za-z']+|[^\w\s]+","",str(a)))

In [282]:
empCost = ['100Rs','Rs200','300$','400INR','500rs']

L = []
for var in empCost:
    r=fx(var)
    L.append(r)
    
L

[100, 200, 300, 400, 500]

In [ ]:
lambda arguments:basicoperation
|
f = lambda a: substitute_operation
f('100Rs')
f('200Rs')
f('300$')

map(function,<collection>) -><generator> => list(geobj) ->[value1,value2,...valueN] ->np.sum()
     |          |
    //lambda,empCost

In [285]:
np.sum(list(map(lambda a:int(re.sub("['A-Za-z']+|[^\w\s]+","",str(a))),empCost)))

1500

In [286]:
if (np.sum(list(map(lambda a:int(re.sub("['A-Za-z']+|[^\w\s]+","",str(a))),empCost))) >2000):
    print('Sum of emp cost is above 2000')
else:
    print('Below 2000')

Below 2000


In [290]:
for line,data in enumerate(open('sysinfo.log'),1):
    if(line >=10 and line <=15):
        print(f'{line} - {data.strip()}')

10 - host07:10.20.30.45:98.45,99,32,90,120,400,99,80.44
11 - host08:10.20.30.46:98.25,99,32,90,120,200,99,90.45
12 - 
13 - 
14 - host09:10.20.30.47:88.45,99,32,90,120,500,99,80.44
15 - host09:10.20.30.47:98.75,99,32,90,120,200,99,80.43


In [293]:
[data.strip() for line,data in enumerate(open('sysinfo.log'),1) if line >=10 and line <= 15]

['host07:10.20.30.45:98.45,99,32,90,120,400,99,80.44',
 'host08:10.20.30.46:98.25,99,32,90,120,200,99,90.45',
 '',
 '',
 'host09:10.20.30.47:88.45,99,32,90,120,500,99,80.44',
 'host09:10.20.30.47:98.75,99,32,90,120,200,99,80.43']

In [294]:
d={}
d['MsgLog']=[data.strip() for line,data in enumerate(open('sysinfo.log'),1) if line >=10 and line <= 15]
d

{'MsgLog': ['host07:10.20.30.45:98.45,99,32,90,120,400,99,80.44',
  'host08:10.20.30.46:98.25,99,32,90,120,200,99,90.45',
  '',
  '',
  'host09:10.20.30.47:88.45,99,32,90,120,500,99,80.44',
  'host09:10.20.30.47:98.75,99,32,90,120,200,99,80.43']}

In [ ]:
json.dumps(d) # convert to json

pd.DataFrame(d) # convert to DataFrame